### ISSUE TITLE
Cant install mp-quic on Linux(fedora/debian) 64bit

### ISSUE THREAD

**Issue by member210** [qdeconinck/mp-quic#1]
Hi
I cant install the server on Linux(fedora 27 /debian 9) 64bit. I use Version 1.9.4 of Go.
If i clone the git repository then enter the directory and finally execute go get -t -u ./... I get the error:
 `unrecognized import path "_/home/test/Downloads/mp-quic" (import path does not begin with hostname)`

I also tried to follow the instructions on https://multipath-quic.org/2017/12/09/artifacts-available.html. But here i always got 
```
[root@localhost quic-go]# go get -t -u ./...
# github.com/lucas-clemente/quic-go/internal/handshake
internal/handshake/mint_utils.go:57:16: mc.conn.State undefined (type *mint.Conn has no field or method State, but does have mint.state)
```
Like i said i tried it on two different distributions with Go 1.9.4 and i tested those two scenarios.

**Comment by qdeconinck** [comment]
The issue
```
[root@localhost quic-go]# go get -t -u ./...
# github.com/lucas-clemente/quic-go/internal/handshake
internal/handshake/mint_utils.go:57:16: mc.conn.State undefined (type *mint.Conn has no field or method State, but does have mint.state)
```
is related to API changes in the mint library since the code was released, as `go get -t -u ./...` fetches the latest commit of all required dependencies.

You can fix this by resetting the mint library to the state it was when the code was released:
```
$ cd $GOPATH/src/github.com/bifurcation/mint
$ git reset --hard a6080d464fb57a9330c2124ffb62f3c233e3400e
```
Then going back to the quic-go directory, `go build` should not raise any error.

I will update the instructions on https://multipath-quic.org/2017/12/09/artifacts-available.html to take this into account.

**Comment by qdeconinck** [comment]
Site and README.md updated.
